name       : libdvbpsi
version    : 1.3.1
release    : 2
source     :
    - https://download.videolan.org/pub/libdvbpsi/1.3.1/libdvbpsi-1.3.1.tar.bz2 : d68367afd5ad8e6ebca813e7958a3ceb9743b421adb4265eceeb6a3511c84420
license    : LGPL-2.1
component  : multimedia.library
summary    : A library designed for decoding and generation of MPEG TS and DVB
description: |
    A library designed for decoding and generation of MPEG TS and DVB PSI tables
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install

