name       : libdvbpsi
version    : 1.3.0
release    : 1
source     :
    - http://download.videolan.org/pub/libdvbpsi/1.3.0/libdvbpsi-1.3.0.tar.bz2 : a2fed1d11980662f919bbd1f29e2462719e0f6227e1a531310bd5a706db0a1fe
license    : LGPL-2.1
component  : multimedia.library
summary    : A library designed for decoding and generation of MPEG TS and DVB
description: |
    A library designed for decoding and generation of MPEG TS and DVB PSI tables
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
