name       : libdvbpsi
version    : 1.3.3
release    : 3
source     :
    - https://download.videolan.org/pub/libdvbpsi/1.3.3/libdvbpsi-1.3.3.tar.bz2 : 02b5998bcf289cdfbd8757bedd5987e681309b0a25b3ffe6cebae599f7a00112
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : A library designed for decoding and generation of MPEG TS and DVB
description: |
    A library designed for decoding and generation of MPEG TS and DVB PSI tables
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
